name: 'Commit Message Checker for pull request'
description: 'Check the commit message in pr against a regex pattern'
author: 'Tim'
inputs:
  token:
    description: 'A token with access to your repository scoped in as a secret'
    required: true
  filter_out_pattern:
    description: 'A regex pattern to check if a commit should be filtered out, empty for disable'
    required: false
    default: ""
  filter_out_flags:
    description: 'Regex flags of input filter_out_pattern'
    required: false
    default: ''
  pattern:
    description: 'A regex pattern to check if a commit message is valid.'
    required: true
  flags:
    description: 'Expression flags change how the expression is interpreted.'
    required: false
    default: ''
  error:
    description: 'A error message which will be returned in case of an error.'
    required: true
  pre_error:
    description: 'A error message which will be showed in the begin of errors.'
    required: false
    default: ''
  post_error:
    description: 'A error message which will be showed in the end of errors.'
    required: false
    default: ''
  one_pass_all_pass:
    description: 'If "true", as long as one commit in the pull-request passes the check, all pass.'
    required: false
    default: "false"

runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'check'
  color: 'blue'
